steps:
- task:  NodeTool@0
  inputs:
    versionSpec: '24.x'
  displayName: 'Install Node.js'
- script: |
    npm install -g @testim/testim-cli
  
  displayName: 'npm install testim-cli'
- script: |
    myBuildNum=$(echo $(Build.BuildNumber) | sed -e 's/^.*\(.\)$/\1/')
    echo "Build Number is : "  $myBuildNum
    testim \
    --token $(TestimToken) \
    --project $(TestimProject) \
    --grid "Testim-Grid" \
    --report-file testim-tests-report.xml \
    --test-plan "Cross Browser" \
    --report-file "testim-report.xml" \
    --parallel 3 \
    --turbo-mode
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'testim-report.xml'
