steps:
- task:  NodeTool@0
  inputs:
    versionSpec: '21.x'
  displayName: 'Install Node.js'
- script: |
    npm install -g @testim/testim-cli
  
  displayName: 'npm install testim-cli'
- script: |
    myBuildNum=$(echo $(Build.BuildNumber) | sed -e 's/^.*\(.\)$/\1/')
    echo "Build Number is : "  $myBuildNum
    testim \
    --token $(TestimToken) \
    --project $(TestimProject) \
    --grid "tricentis-device-cloud" \
    --report-file testim-tests-report.xml \
    --test-plan "AzureDevops" \
    --report-file "testim-report.xml" \
    --parallel 3 \
    --result-label "AzureDevops Build:  $(Date:yyyyMMdd).$(Rev:r)" \
    --turbo-mode
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'testim-report.xml'
